### ISSUE TITLE
Why not react?

### ISSUE THREAD

**Issue by rotatordisk92** [Atraci/Atraci-New#1]
Long time no see, my friend.
I was about to start contributing but then I noticed the package.json

I was just wondering why you decided to go with this tech stack?

**Comment by avihaymenahem** [comment]
I Personally know angular a bit more than react, not any special reason :)

**Comment by rotatordisk92** [comment]
@avihaymenahem
No electron?

**Comment by avihaymenahem** [comment]
sure we will have electron, developing everything i need before, and then insert it :)
